Repository pfnet-research/chainer-chemistry, pull requests merged in 2018-12, with the labels that each got.

#280 Rename `device_id` inside `BaseForwardModel`
  chainer_chemistry/models/prediction/base.py
Labels: bug, no-compat

#282 Report metrics as scalars
  chainer_chemistry/models/prediction/classifier.py
  chainer_chemistry/models/prediction/regressor.py
  examples/own_dataset/predict_own_dataset.py
  examples/qm9/predict_qm9.py
Labels: bug

#270 Arrange `links` modules
  chainer_chemistry/functions/__init__.py
  chainer_chemistry/functions/evaluation/__init__.py
  chainer_chemistry/functions/evaluation/r2_score.py
  chainer_chemistry/functions/loss/__init__.py
  chainer_chemistry/functions/loss/mean_absolute_error.py
  chainer_chemistry/functions/loss/mean_squared_error.py
  chainer_chemistry/functions/math/__init__.py
  chainer_chemistry/functions/math/matmul.py
  chainer_chemistry/functions/readout/__init__.py
  chainer_chemistry/functions/readout/general_readout.py
  chainer_chemistry/links/__init__.py
  chainer_chemistry/links/connection/__init__.py
  chainer_chemistry/links/connection/embed_atom_id.py
  chainer_chemistry/links/connection/graph_linear.py
  chainer_chemistry/links/normalization/__init__.py
  chainer_chemistry/links/normalization/graph_batch_normalization.py
  chainer_chemistry/links/readout/__init__.py
  chainer_chemistry/links/readout/ggnn_readout.py
  chainer_chemistry/links/readout/nfp_readout.py
  chainer_chemistry/links/readout/schnet_readout.py
  chainer_chemistry/links/update/__init__.py
  chainer_chemistry/links/update/ggnn_update.py
  chainer_chemistry/links/update/nfp_update.py
  chainer_chemistry/links/update/relgcn_update.py
  chainer_chemistry/links/update/rsgcn_update.py
  chainer_chemistry/links/update/schnet_update.py
  chainer_chemistry/models/ggnn.py
  chainer_chemistry/models/nfp.py
  chainer_chemistry/models/relgcn.py
  chainer_chemistry/models/rsgcn.py
  chainer_chemistry/models/schnet.py
  chainer_chemistry/models/weavenet.py
  tests/functions_tests/evaluation/test_r2_score.py
  tests/functions_tests/loss/test_mean_absolute_error.py
  tests/functions_tests/loss/test_mean_squared_error.py
  tests/functions_tests/readout/test_general_readout.py
  tests/links_tests/connection_tests/test_embed_atom_id.py
  tests/links_tests/readout_tests/test_ggnn_readout.py
  tests/links_tests/readout_tests/test_nfp_readout.py
  tests/links_tests/readout_tests/test_schnet_readout.py
  tests/links_tests/update_tests/test_ggnn_update.py
  tests/links_tests/update_tests/test_nfp_update.py
  tests/links_tests/update_tests/test_relgcn_update.py
  tests/links_tests/update_tests/test_rsgcn_update.py
  tests/links_tests/update_tests/test_schnet_update.py
  tests/models_tests/prediction_tests/test_classifier.py
  tests/models_tests/prediction_tests/test_regressor.py
  tests/models_tests/test_rsgcn.py
Labels: no-compat
